apiVersion: v1
kind: Pod
metadata:
  name: env-test
spec:
 containers:
  - name: nginx
    image: nginx:1.14.2
    env:
    - name: course
      value: 'Kubernetes'
    - name: duration
      value: '20hours'

