apiVersion: v1
kind: Pod
metadata:
  name: env-test
spec:
 containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
    # soft limit
      requests: 
        memory: "128Mi"
        cpu: "100m"
    # limits should be atleast or more than requests i.e hard limit
      limits:
        memory: "128Mi"
        cpu: "100m"

