apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec:
 containers:
  - name: nginx
    image: nginx:1.14.2
    envFrom:
    - configMapRef:
       name: configmap

    # env: 
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: config-map
    #       key: course
    # - name: trainer
    #   valueFrom:
    #     configMapKeyRef:
    #       name: config-map
    #       key: trainer          
