apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    name: frontend
    project: expense
    componet: frontend
    environment: dev
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2