apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    name: frontend
    project: expense
    componet: frontend
    environment: dev
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port 
    nodePort: 32760